### ISSUE TITLE
Not Working for Laravel 5

### ISSUE THREAD

**Issue by sonusbeat** [lookitsatravis/listify#10]
BadMethodCallException] 
Call to undefined method [package]

Laravel Framework version 5.0.14

IT'S NOT WORKING THIS PACKAGE FOR THIS LARAVEL VERSION

**Comment by lookitsatravis** [comment]
Hello @sonusbeat. Can you give me an example of the code you're trying to run?

**Comment by sonusbeat** [comment]
I Just Follow the instructions from https://github.com/lookitsatravis/listify

// composer.json
......
require": {
  "laravel/framework": "5.0.*",
  "illuminate/html": "~5.0",
  "doctrine/dbal": "~2.5",
  "lookitsatravis/listify": "1.0.*",
  "intervention/imagecache": "2.1.*",
  "orchestra/parser": "3.0.*"
},

// config/app.php
...
'Illuminate\Validation\ValidationServiceProvider',
'Illuminate\View\ViewServiceProvider',
'Illuminate\Html\HtmlServiceProvider',

/**
   * Third Party Providers
  */
'Laracasts\Generators\GeneratorsServiceProvider',
'Lookitsatravis\Listify\ListifyServiceProvider',
....
'aliases' => [
.....
'View'      => 'Illuminate\Support\Facades\View',
'Form'      => 'Illuminate\Html\FormFacade',
'Html'      => 'Illuminate\Html\HtmlFacade',
'Listify' => 'Lookitsatravis\Listify\Listify',
'Image' => 'Intervention\Image\Facades\Image',
....

And if I write php artisan allways gives me the following error:

BadMethodCallException] 
Call to undefined method [package]

**Comment by willishq** [comment]
Laravel 5 has changed the way that it handles packages, the service provider needs modifying to mirror this, although I will say that this package in no place says it supports Laravel 5 so assuming it to be the case would be foolish in my opinion, since so many packages are not yet supported on Laravel 5.

**Comment by lookitsatravis** [comment]
Yep, I didn't explicitly update it to work with Laravel 5 yet. But, I know what the issue is and will work on it as soon as I can. I wonder if I can support L4 and L5 in the same release without being too hacky about it.

**Comment by lookitsatravis** [comment]
I've opened an issue on laravel/framework to discuss how a package can get the version of Laravel and behave differently. You can see it here (https://github.com/laravel/framework/issues/7924), but basically this package will be unchanged except for these package registration differences. I'd like to continue to support L4 without having to maintain a separate branch if possible, but this will only happen if we can somehow know the Laravel version from within the package.

Currently, the Laravel Version is only available from Illuminate\Foundation\Application, which is not a package that can be required via composer, at least not without requiring the entire Illuminate\Framework package. I'd like to avoid that if I can and stick with Illuminate\Support. I want to see if this conversation goes anywhere before I make a breaking change, so hopefully I'll find out soon.

Sorry for the troubles!

**Comment by sonusbeat** [comment]
Thanks Man for taking your time for answering, I will wait for complete compatibility, great job by the way, greetings from Mexico

**Comment by willishq** [comment]
If you want to maintain support for Laravel 4 (even though it will be
deprecated in the near future if it hasn't already) the best thing in my
opinion would be to create a separate service provider for Laravel 5

On Tuesday, March 10, 2015, sonusbeat <notifications@github.com> wrote:

> Thanks Man for taking your time for answering, I will wait for complete
> compatibility, great job by the way, greetings from Mexico
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lookitsatravis/listify/issues/10#issuecomment-77990046>
> .
>


-- 
Andrew Willis
Technical Web Developer

andrew@willisilliw.com | 07842 521 806

uk.linkedin.com/in/willisilliw/
