### ISSUE TITLE
Listify booted twice on model

### ISSUE THREAD

**Issue by xire28** [lookitsatravis/listify#12]
Listify is overriding **boot** model method to boot his behaviour, this is now deprecated for obvious reasons.

Now Eloquent traits must use a different system to boot themself. Every trait method starting with **boot** is automatically called by Eloquent then a model is booting.

So currently **boot** and **bootListify** are both called independently then a model is booting.

**Comment by lookitsatravis** [comment]
Thanks for pointing this out. I've done a new minor release (1.1.1) that removes the references to overriding the boot method. Also, thanks for the PR. Cheers!

:+1:
