### ISSUE TITLE
[Bug] `setListPosition` not work on database connection with `prefix`

### ISSUE THREAD

**Issue by trungtnm** [lookitsatravis/listify#14]
When use `setListPosition()` on a database connection with `prefix` config, we will received an error that the `primary key` field of Eloquent model is not matched with its database prefix.

And this bugs will be fixed if we change this line of code
```
     /**
     * Returns the primary key of the current Eloquent instance
     * @return string
     */
    private function primaryKey()
    {
        return $this->getConnection()->getTablePrefix() . $this->getQualifiedKeyName();
    }
```

**Comment by lookitsatravis** [comment]
@trungtnm - Thanks for the report. If you'd like to submit a pull request, I'd be happy to merge it in and tag a release. I won't have the capacity to work on it for a couple of weeks, though.

**Comment by lookitsatravis** [comment]
@trungtnm - I was able to add this into master, and I'll tag a release later this morning. Thanks for notifying me!

**Comment by trungtnm** [comment]
It has been a long time i do not visit Github and not see your comments. I'm sorry about that and very glad to hear about this issue has resovled.
