### ISSUE TITLE
Double-quotes in query from Query Builder scope causing Postgres error

### ISSUE THREAD

**Issue by ccwittwer** [lookitsatravis/listify#16]
when getConditionStringFromQueryBuilder builds $theQuery (line 253), it's using double-quotes, which Postgres sees as a system identifier.

so `where "type" = "internal"` throws an error saying that the column "internal" does not exist.
changing it to single-quotes, as in `where "type" = 'internal'`, fixes the issue

Potential solution for Postgres queries:

LINE 253:

```
$theQuery .= '\'' . $bindings[$i] . '\'';
```

**Comment by lookitsatravis** [comment]
Closed with #19 (thanks to @stevendesu)
