### ISSUE TITLE
Inifinite loop when scoping to a self-reference

### ISSUE THREAD

**Issue by jordanlev** [lookitsatravis/listify#20]
I've got a hierarchical structure of pages in a site, so my model has a "belongsTo" relationship to itself (child page points to its parent page, and vice-versa). I want the position to be scoped within each parent, so users can sort pages within their parent... but since I am calling the "belongsTo" method in the model constructor, it just keeps calling this over and over again for each parent (eventually the parent's refer to themselves at the "root" of the hierarchy).

I tried a few workarounds (using a string to specify the parent id, having the relationship method only call `$this->belongsTo()` when parent is not null)... but they all rely on the model knowing its parent id and unfortunately that data isn't available yet in the model constructor. Any other ideas on how I might address this problem?

Thanks.

**Comment by lookitsatravis** [comment]
@jordanlev - Thanks for the info. Do you have a code sample you can provide, or a sample app I can clone?

Thanks!

**Comment by jordanlev** [comment]
Here's a distilled version of the model class:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model {
	public $timestamps = false;
	
	use \Lookitsatravis\Listify\Listify;
	
	public function __construct(array $attributes = []) {
		parent::__construct($attributes);
		$this->initListify([
			'scope' => $this->parent_category()
		]);
	}
	
	public function child_categories() {
		return $this->hasMany('App\ProductCategory', 'parent_id');
	}
	
	public function parent_category() {
		return $this->belongsTo('App\ProductCategory', 'parent_id');
	}
	
}
```

And here's the migration that creates the underlying table:
```
Schema::create('product_categories', function (Blueprint $table) {
	$table->increments('id');
	$table->integer('parent_id')
		  ->unsigned()
		  ->nullable()
		  ->index();
	$table->string('title');
	$table->integer('position')
		  ->unsigned();
	
	$table->foreign('parent_id')
		  ->references('id')
		  ->on('product_categories')
		  ->onDelete('cascade');
});
```

**Comment by lookitsatravis** [comment]
Great, I appreciate that. So, to make sure I'm understanding this clearly, with that particular scope in the code, any time the ProductCategory class is used, there is an infinite loop on that line in the constructor? Or is there a certain way that this class is used (e.g. as part of query or some method call in a controller) which causes it?

**Comment by lookitsatravis** [comment]
Oh, in addition to the above, @jordanlev - what version of Laravel are you using?

**Comment by jordanlev** [comment]
I'm using Laravel 5.4. And the issue occurs any time the model is instantiated (e.g. `ProductCategory::find(1)`, or `ProductCategory::all()`, or `$x = new ProductCategory($request->all())`)

Thanks for your assistance.

**Comment by lookitsatravis** [comment]
@jordanlev Thanks for the information. I'll take a look as soon as I can and get back to you.

**Comment by jordanlev** [comment]
I figured out a solution by altering the Listify Trait to allow for the scope to be a callback (anonymous function / closure). This works in combination with the following code in my model:

```
public function __construct(array $attributes = []) {
	parent::__construct($attributes);
	
	$this->initListify([
		'scope' => function($model) {
			return $model->parent_id ? $model->parent_category() : 'parent_id IS NULL';
		},
	]);
}
```

I submitted that PR more as a way to show you the change -- I am not sure if there are unintended side-effects or whatnot (so I won't be offended if you don't merge it :)

This was the quickest solution I could get to work, but I don't think it's very elegant. I wonder if it would be better to not have to override the constructor at all, but rather the Listify Trait could call a method on the model that returns the config options (and this would be called only when needed, in the `scopeCondition()` method, not in the constructor). The benefit of this is then you're not overriding the constructor in your models (which feels kind of "unsafe" to me, since it's not a generally-accepted thing to do in Eloquent models). But the big drawback of course is that it's a major breaking change in how Listify works. Maybe there's a way to keep the old functionality too though?

Thanks for the great module!

**Comment by jordanlev** [comment]
Well, that was quite the journey of discovery! But it turns out I found a way to avoid the problem that doesn't involve changing the Listify code.

I am declaring my scope in the model like so:
```
public function scopeName()
{
	if ($this->listifyConfig['scope'] === $this->defaultScope) {
		$this->listifyConfig['scope'] = $this->parent_id ? $this->parent_category() : 'parent_id IS NULL';
	}
	
	return $this->listifyConfig['scope'];
}
```

Still kind of hacky, but at least I'm only hacking up my model and not the base Listify trait :)

If you have any more insight, I'd love to hear it -- otherwise I'll consider this solved. Thanks!

**Comment by eminos** [comment]
@jordanlev Im having the exact same issue as you had. Same scenario with product_categories. How do you invoke that `scopeName()` method? In the constructor like this?

```
public function __construct(array $attributes = [], $exists = false) {
        parent::__construct($attributes, $exists);

        $this->initListify([
            'column' => 'index',
            'scope' => $this->scopeName()
        ]);

    }
```

What is `$this->defaultScope()`?
Could you please help me understand the code? :)

**Comment by lookitsatravis** [comment]
Closing all issues due to inactivity of this project. The repository will be archived shortly. Thanks for understanding.
