### ISSUE TITLE
Status of Laravel 6/7 release in develop branch

### ISSUE THREAD

**Issue by erikgall** [lookitsatravis/listify#29]
Hey @lookitsatravis,

I hope you're doing well man. Clay and I are working on getting the Clarus app upgraded to Laravel 7 and are currently sitting at v6.0 (https://github.com/eClinicHealthcare/eclinic-api/pull/121). I was digging around the codebase last night and stumbled upon the `develop` branch which it looks like you upgraded to be compatible w/ the newer versions of Laravel but never released.

I was wondering what the status of the `develop` branch is? I don't see anything in the codebase that would cause problems w/ Laravel (everything looks pretty solid to me) but would it be possible for you to tag it as a new release (and possibly add Laravel 7 support via dependency requirement)? If there are things left to do before it works 100%, I can take care of whatever those things are and send a PR you way as well 😄.

Thanks!

**Comment by lookitsatravis** [comment]
Hey @erikgall! I saw your PR over the weekend. I haven’t had a chance to review it, but I will and get back to you this week. The develop branch was/is close to release. I just got sidetracked. 🤷‍♂️

Thanks for your help on this!

**Comment by erikgall** [comment]
@lookitsatravis  No problem. From what I could tell your develop branch was pretty solid as far as working correctly. The only thing I could find was the Laravel command wasn't working. In my PR that is really the only big change. It got tested out in the Clarus app as well and was working great.

**Comment by lookitsatravis** [comment]
Closing all issues due to inactivity of this project. The repository will be archived shortly. Thanks for understanding.
